query Fetch
{
  queryDirectivebodyContents {
   id
  
  data: flatData {
    governmentModelTitle
    governmentModelDescription
    governmentModel {
      schemaName
      title
      list {
        name
        position
        description
        image {
          id
          url
        }
      }
    }
  }
 }
}