query Fetch
{
  queryGovernmentModelContents {
    data: flatData {
      banner {
        title
        subtitle
        description

        button {
          label
          link
        }
        
        image {
          id
          url
        }
      }

      about {
        title
        description
        
        image {
          url
        }
      }

      governmentModelTitle
      governmentModelDescription
      
      governmentModel {
        title
        
        list {
          name
          position
        }
      }
    }
  }
}