query Fetch {
  queryHomepageContents {
    data: flatData {
      banner {
        title
        subtitle
        description

        button {
          label
          link
        }

        image {
          id
          url
        }
      }

      shortcuts {
        title
        description
        link

        icon {
          url
        }
      }

      cards {
        title
        description

        button {
          label
          link
        }

        features {
          feature
        }

        frontSideImage {
          url
        }

        backSideImage {
          url
        }
      }

      financialTips {
        id
        created

        data: flatData {
          title
          excerpt

          image {
            url
          }
        }
      }

      simuladorDP {
        id
        data: flatData {
          icon {
            id
            url
          }
          title
          min
          max
          juros
          file {
            id
            url
          }
          timeline {
            tempo
            rate
            day
            month
          }
        }
      }

      simuladorCredito {
        id
        data: flatData {
          icon {
            id
            url
          }

          file {
            id
            url
          }
          title
          min
          max
          juros
        }
      }
    }
  }
}
