query Fetch
{
  queryCareersContents {
    data: flatData {
      banner {
        title
        subtitle
        description

        button {
          label
          link
        }
        
        image {
          id
          url
        }
      }

      humanCapitalTitle
      humanCapitalDescription
      
      humanCapital {
        title
        subtitle
        description

        button {
          label
          link
        }

        image {
          url
        }
      }


 charts {
     id
   data: flatData {
      title
      titleChart
      icon {
        url
      }
      descriptionChart
      typeChart
      
      informations {
        value
        descriptonChat
      }
    }
   }
    }



  }
}